name: Refresh PHIVOLCS charts and pages
on:
schedule:
- cron: "0 18 * * *"
workflow_dispatch:

jobs:
build:
runs-on: ubuntu-latest
permissions:
contents: write
env:
KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
steps:

    name: Checkout
    uses: actions/checkout@v4

    name: Set up Python
    uses: actions/setup-python@v5
    with:
    python-version: "3.11"

    name: Install dependencies
    run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

    name: Generate charts and HTML
    run: |
    python ph-earthquake-analysis.py

    name: Commit updated docs
    run: |
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    git add docs/*
    git diff --cached --quiet || git commit -m "chore(data): refresh charts and leaders summary from latest PHIVOLCS"
    git push

